/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugEnterprise;

import UserInterface.DrugEnterprise.Compound.NewCompoundPanel;
import UserInterface.DrugEnterprise.Compound.UpdateCompoundPanel;
import UserInterface.DrugEnterprise.Compound.ViewCompoundHistoryPanel;
import UserInterface.DrugEnterprise.DruggistRole.NewDrugPanel;
import UserInterface.DrugEnterprise.DruggistRole.UpdateDrugPanel;
import UserInterface.DrugEnterprise.DruggistRole.ViewDrugHistoryPanel;
import UserInterface.DrugEnterprise.ResearcherRole.NewMsgPanel;
import UserInterface.DrugEnterprise.ResearcherRole.NewStudyPanel;
import UserInterface.DrugEnterprise.ResearcherRole.ResearcherChannelPanel;
import UserInterface.DrugEnterprise.ResearcherRole.UpdateStudyPanel;
import UserInterface.DrugEnterprise.ResearcherRole.ViewStudyHistoryPanel;
import UserInterface.HospitalEnterprise.HospitalJFrame;
import UserInterface.SystemAdminWorkArea.SystemAdminJFrame;
import dao.DrugGraphDataDao;
import dao.UserDao;
import entities.DrugGraphData;
import entities.User;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jdatepicker.DatePanel;
import org.jdatepicker.JDatePanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.util.Rotation;

/**
 *
 * @author GladysWang
 */
public class DrugEnterprise extends javax.swing.JFrame {

    /**
     * Creates new form DrugEnterprise
     */
    JPanel userProcessContainer;

    public DrugEnterprise() {

        setExtendedState(JFrame.MAXIMIZED_BOTH);

        initComponents();
//        initCalender();
        initUserInfo();
        showChar();

    }
    private ChartPanel chartPanel;

    public void showChar() {
        PieDataset dataset = patientsRegDataset();
        JFreeChart chart = createPatientsRegChart(dataset, "Drug Statistics");
        chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(400, 300));
        pChart.add(chartPanel);
    }

    private JFreeChart createPatientsRegChart(PieDataset dataset, String title) {
        JFreeChart chart = ChartFactory.createPieChart(title, dataset, true, true, false);

        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setStartAngle(0);
        plot.setDirection(Rotation.CLOCKWISE);
        plot.setForegroundAlpha(0.5f);

        return chart;
    }

    private PieDataset patientsRegDataset() {
        DefaultPieDataset result = new DefaultPieDataset();
        DrugGraphDataDao pc = new DrugGraphDataDao();
        List<DrugGraphData> list = pc.getPatientAdmissionYearMonth();
        for (DrugGraphData dgd : list) {
            String months = dgd.getCompoundName();
            Integer patients = dgd.getCompoundUsedNumber().intValue();
            result.setValue(months, patients);
        }
        return result;
    }

    public void initUserInfo() {
        User user = UserDao.getUser();
        lbEnterprise.setText(new UserDao().getEnterpriseNameById(user.getIdEnterprise() + ""));
        lbRole.setText(user.getRole());
        lbUser.setText(user.getUsername());
    }

    public void initCalender() {
        DatePanel panel = new JDatePanel();
        panel.setShowYearButtons(true);
        pCal.add((Component) panel);

//        pCal.add((JComponent) panel);
        panel.setShowYearButtons(false);
        pCal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        innerSplitPane = new javax.swing.JSplitPane();
        upperPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbRole = new javax.swing.JLabel();
        lbEnterprise = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        downPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        up = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pFunction = new javax.swing.JPanel();
        btnViewCompoundHis = new javax.swing.JButton();
        btnNewCompound = new javax.swing.JButton();
        btnUpdateCompound = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnViewDrugHis = new javax.swing.JButton();
        btnNewDrug = new javax.swing.JButton();
        btnUpdateDrug = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        sendMsgBtn = new javax.swing.JButton();
        btnNewStudy = new javax.swing.JButton();
        btnUpdateStudy = new javax.swing.JButton();
        down = new javax.swing.JPanel();
        pCal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        ppFunction = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pChart = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        tabSwitchAccount = new javax.swing.JMenu();
        tabHome1 = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        tabHome = new javax.swing.JMenuItem();
        jSeparator22 = new javax.swing.JPopupMenu.Separator();
        tabExit = new javax.swing.JMenuItem();
        tabNewStudy1 = new javax.swing.JMenu();
        tabNewCompound = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        tabUpdateCompound = new javax.swing.JMenuItem();
        tabUpdateStudy1 = new javax.swing.JPopupMenu.Separator();
        tabShowCompoundHis = new javax.swing.JMenuItem();
        tabNewDrug = new javax.swing.JMenu();
        tabHelp = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        tabUpdateDrug = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        tabShowDrugHis = new javax.swing.JMenuItem();
        tabNewStudy = new javax.swing.JMenu();
        tabHelp1 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        tabAbout2 = new javax.swing.JMenuItem();
        tabUpdateStudy = new javax.swing.JPopupMenu.Separator();
        tabShowStudyHis = new javax.swing.JMenuItem();
        tabMessage = new javax.swing.JMenu();
        tabNewMsg = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        tabShowChannel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 650));

        jSplitPane.setDividerLocation(250);
        jSplitPane.setDividerSize(5);
        jSplitPane.setPreferredSize(new java.awt.Dimension(1000, 650));

        leftPanel.setPreferredSize(new java.awt.Dimension(300, 650));
        leftPanel.setLayout(new java.awt.BorderLayout());

        innerSplitPane.setDividerLocation(180);
        innerSplitPane.setDividerSize(0);
        innerSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        innerSplitPane.setMinimumSize(new java.awt.Dimension(200, 650));
        innerSplitPane.setPreferredSize(new java.awt.Dimension(250, 336));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Welcome!");

        lbRole.setText("Gruggist");

        lbEnterprise.setText("Research Instute:");

        lbUser.setText("Gladys");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/0.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbRole)
                        .addGap(37, 37, 37)
                        .addComponent(lbUser))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbEnterprise))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel12))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRole)
                    .addComponent(lbUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEnterprise)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        innerSplitPane.setTopComponent(upperPanel);

        downPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        downPanel.setLayout(new java.awt.CardLayout());

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(200, 400));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(250, 300));

        btnViewCompoundHis.setText("View Compound History");
        btnViewCompoundHis.setPreferredSize(new java.awt.Dimension(110, 29));
        btnViewCompoundHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCompoundHisActionPerformed(evt);
            }
        });

        btnNewCompound.setText("New Compound");
        btnNewCompound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCompoundActionPerformed(evt);
            }
        });

        btnUpdateCompound.setText("Update Compound");
        btnUpdateCompound.setPreferredSize(new java.awt.Dimension(110, 29));
        btnUpdateCompound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCompoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFunctionLayout = new javax.swing.GroupLayout(pFunction);
        pFunction.setLayout(pFunctionLayout);
        pFunctionLayout.setHorizontalGroup(
            pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFunctionLayout.createSequentialGroup()
                .addGroup(pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewCompoundHis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateCompound, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewCompound, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pFunctionLayout.setVerticalGroup(
            pFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFunctionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnNewCompound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateCompound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewCompoundHis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Compound", pFunction);

        btnViewDrugHis.setText("View Drug History");
        btnViewDrugHis.setPreferredSize(new java.awt.Dimension(110, 29));
        btnViewDrugHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDrugHisActionPerformed(evt);
            }
        });

        btnNewDrug.setText("New Drug");
        btnNewDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDrugActionPerformed(evt);
            }
        });

        btnUpdateDrug.setText("Update Drug");
        btnUpdateDrug.setPreferredSize(new java.awt.Dimension(110, 29));
        btnUpdateDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDrugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewDrugHis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateDrug, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewDrug, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnNewDrug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateDrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewDrugHis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Drug", jPanel7);

        sendMsgBtn.setText("Send Message To Doctor");
        sendMsgBtn.setPreferredSize(new java.awt.Dimension(110, 29));
        sendMsgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMsgBtnActionPerformed(evt);
            }
        });

        btnNewStudy.setText("New Study");
        btnNewStudy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewStudyActionPerformed(evt);
            }
        });

        btnUpdateStudy.setText("Update Study");
        btnUpdateStudy.setPreferredSize(new java.awt.Dimension(110, 29));
        btnUpdateStudy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStudyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sendMsgBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateStudy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewStudy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnNewStudy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateStudy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendMsgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Study", jPanel4);

        javax.swing.GroupLayout upLayout = new javax.swing.GroupLayout(up);
        up.setLayout(upLayout);
        upLayout.setHorizontalGroup(
            upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(upLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        upLayout.setVerticalGroup(
            upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(upLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jSplitPane1.setTopComponent(up);

        down.setLayout(new java.awt.BorderLayout());

        pCal.setBackground(new java.awt.Color(204, 204, 204));
        pCal.setForeground(new java.awt.Color(204, 204, 204));
        pCal.setAlignmentX(0.0F);
        pCal.setAlignmentY(0.0F);
        pCal.setMinimumSize(new java.awt.Dimension(230, 234));
        pCal.setPreferredSize(new java.awt.Dimension(240, 220));
        pCal.setLayout(new java.awt.BorderLayout());

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/research_technology_drug-interaction.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pCal.add(jPanel2, java.awt.BorderLayout.CENTER);

        down.add(pCal, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(down);

        downPanel.add(jSplitPane1, "card2");

        innerSplitPane.setRightComponent(downPanel);

        leftPanel.add(innerSplitPane, java.awt.BorderLayout.CENTER);

        jSplitPane.setLeftComponent(leftPanel);

        container.setLayout(new java.awt.CardLayout());

        ppFunction.setPreferredSize(new java.awt.Dimension(252, 180));
        ppFunction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel1.setText("WEEK'S KNOWLEDGE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 300, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(238, 238, 238));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Drug-Drug Interaction can be a serious problem, as many \ndiseases are treated with multiple medications. \nDrug-drug interaction typically occurs when two co-administered medicines use the same biological route of active   absorption or elimination or when one of the two drugs acts as an inhibitor or an activator for the elimination route of\n the other. \n\nThis can lead to unwanted overdosing of one of the two \ndrugs, causing safety issues, or it can make one of the two drugs ineffective.");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 650, 220));

        pChart.setPreferredSize(new java.awt.Dimension(200, 200));
        pChart.setLayout(new java.awt.CardLayout());
        jPanel1.add(pChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 520, 340));

        ppFunction.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 650));

        container.add(ppFunction, "card2");

        jSplitPane.setRightComponent(container);

        getContentPane().add(jSplitPane, java.awt.BorderLayout.CENTER);

        tabSwitchAccount.setText("EcoSystem");

        tabHome1.setText("System Admin");
        tabHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabHome1ActionPerformed(evt);
            }
        });
        tabSwitchAccount.add(tabHome1);
        tabSwitchAccount.add(jSeparator20);

        tabHome.setText("Hospital");
        tabHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabHomeActionPerformed(evt);
            }
        });
        tabSwitchAccount.add(tabHome);
        tabSwitchAccount.add(jSeparator22);

        tabExit.setText("Exit");
        tabExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabExitActionPerformed(evt);
            }
        });
        tabSwitchAccount.add(tabExit);

        jMenuBar1.add(tabSwitchAccount);

        tabNewStudy1.setText("Compound");

        tabNewCompound.setText("New Compound");
        tabNewCompound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabNewCompoundActionPerformed(evt);
            }
        });
        tabNewStudy1.add(tabNewCompound);
        tabNewStudy1.add(jSeparator18);

        tabUpdateCompound.setText("Update Compound");
        tabUpdateCompound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabUpdateCompoundActionPerformed(evt);
            }
        });
        tabNewStudy1.add(tabUpdateCompound);
        tabNewStudy1.add(tabUpdateStudy1);

        tabShowCompoundHis.setText("Show Compound History");
        tabShowCompoundHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabShowCompoundHisActionPerformed(evt);
            }
        });
        tabNewStudy1.add(tabShowCompoundHis);

        jMenuBar1.add(tabNewStudy1);

        tabNewDrug.setText("Drug");

        tabHelp.setText("New Drug");
        tabHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabHelpActionPerformed(evt);
            }
        });
        tabNewDrug.add(tabHelp);
        tabNewDrug.add(jSeparator3);

        tabUpdateDrug.setText("Update Drug");
        tabUpdateDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabUpdateDrugActionPerformed(evt);
            }
        });
        tabNewDrug.add(tabUpdateDrug);
        tabNewDrug.add(jSeparator14);

        tabShowDrugHis.setText("Show Drug History");
        tabShowDrugHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabShowDrugHisActionPerformed(evt);
            }
        });
        tabNewDrug.add(tabShowDrugHis);

        jMenuBar1.add(tabNewDrug);

        tabNewStudy.setText("Study");

        tabHelp1.setText("New Study");
        tabHelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabHelp1ActionPerformed(evt);
            }
        });
        tabNewStudy.add(tabHelp1);
        tabNewStudy.add(jSeparator17);

        tabAbout2.setText("Update Study");
        tabAbout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabAbout2ActionPerformed(evt);
            }
        });
        tabNewStudy.add(tabAbout2);
        tabNewStudy.add(tabUpdateStudy);

        tabShowStudyHis.setText("Show Study History");
        tabShowStudyHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabShowStudyHisActionPerformed(evt);
            }
        });
        tabNewStudy.add(tabShowStudyHis);

        jMenuBar1.add(tabNewStudy);

        tabMessage.setText("Message");

        tabNewMsg.setText("Send New Message");
        tabNewMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabNewMsgActionPerformed(evt);
            }
        });
        tabMessage.add(tabNewMsg);
        tabMessage.add(jSeparator21);

        tabShowChannel.setText("Show Channel");
        tabShowChannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabShowChannelActionPerformed(evt);
            }
        });
        tabMessage.add(tabShowChannel);

        jMenuBar1.add(tabMessage);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabHelpActionPerformed
        NewDrugPanel panel = new NewDrugPanel(container);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("NewDrugPanel", panel);
        layout.next(container);
    }//GEN-LAST:event_tabHelpActionPerformed

    private void tabUpdateDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabUpdateDrugActionPerformed
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("UpdateDrugPanel", new UpdateDrugPanel(container));
        layout.next(container);
    }//GEN-LAST:event_tabUpdateDrugActionPerformed

    private void tabExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabExitActionPerformed

    private void tabShowDrugHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabShowDrugHisActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ViewDrugHistoryPanel", new ViewDrugHistoryPanel(container));
        layout.next(container);
    }//GEN-LAST:event_tabShowDrugHisActionPerformed

    private void tabHelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabHelp1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("NewStudyPanel", new NewStudyPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_tabHelp1ActionPerformed

    private void tabAbout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabAbout2ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("UpdateStudyPanel", new UpdateStudyPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_tabAbout2ActionPerformed

    private void tabShowStudyHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabShowStudyHisActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ViewStudyHistoryPanel", new ViewStudyHistoryPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_tabShowStudyHisActionPerformed

    private void tabNewCompoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabNewCompoundActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("NewCompoundPanel", new NewCompoundPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_tabNewCompoundActionPerformed

    private void tabUpdateCompoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabUpdateCompoundActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("UpdateCompoundPanel", new UpdateCompoundPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_tabUpdateCompoundActionPerformed

    private void tabShowCompoundHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabShowCompoundHisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabShowCompoundHisActionPerformed

    private void tabHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabHomeActionPerformed

        try {
            new HospitalJFrame().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(HospitalJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(HospitalJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        System.gc();

        // TODO add your handling code here:
    }//GEN-LAST:event_tabHomeActionPerformed

    private void btnViewCompoundHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCompoundHisActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ViewCompoundHistoryPanel", new ViewCompoundHistoryPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_btnViewCompoundHisActionPerformed

    private void btnNewCompoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCompoundActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("NewCompoundPanel", new NewCompoundPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_btnNewCompoundActionPerformed

    private void btnUpdateCompoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCompoundActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("UpdateCompoundPanel", new UpdateCompoundPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_btnUpdateCompoundActionPerformed

    private void btnViewDrugHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDrugHisActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ViewDrugHistoryPanel", new ViewDrugHistoryPanel(container));
        layout.next(container);
    }//GEN-LAST:event_btnViewDrugHisActionPerformed

    private void btnNewDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDrugActionPerformed
        // TODO add your handling code here:
        NewDrugPanel panel = new NewDrugPanel(container);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("NewDrugPanel", panel);
        layout.next(container);
    }//GEN-LAST:event_btnNewDrugActionPerformed

    private void btnUpdateDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDrugActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("UpdateDrugPanel", new UpdateDrugPanel(container));
        layout.next(container);
    }//GEN-LAST:event_btnUpdateDrugActionPerformed

    private void sendMsgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMsgBtnActionPerformed
        //        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ViewStudyHistoryPanel", new ViewStudyHistoryPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_sendMsgBtnActionPerformed

    private void btnNewStudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewStudyActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("NewStudyPanel", new NewStudyPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_btnNewStudyActionPerformed

    private void btnUpdateStudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStudyActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("UpdateStudyPanel", new UpdateStudyPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_btnUpdateStudyActionPerformed

    private void tabHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabHome1ActionPerformed

        new SystemAdminJFrame().setVisible(true);

        dispose();
        System.gc();

        // TODO add your handling code here:
    }//GEN-LAST:event_tabHome1ActionPerformed

    private void tabNewMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabNewMsgActionPerformed
        //deleted this part since we use panel
        //        try {
        //            NewMsgFrame panel = new NewMsgFrame();
        //            panel.setVisible(true);
        //        } catch (SQLException ex) {
        //            Logger.getLogger(UpdateDrugPanel.class.getName()).log(Level.SEVERE, null, ex);
        //        }
        //

        CardLayout layout = (CardLayout) container.getLayout();
        container.add("NewMsgPanel", new NewMsgPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_tabNewMsgActionPerformed

    private void tabShowChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabShowChannelActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ResearcherChannelPanel", new ResearcherChannelPanel(userProcessContainer));
        layout.next(container);
    }//GEN-LAST:event_tabShowChannelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrugEnterprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrugEnterprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrugEnterprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrugEnterprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrugEnterprise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewCompound;
    private javax.swing.JButton btnNewDrug;
    private javax.swing.JButton btnNewStudy;
    private javax.swing.JButton btnUpdateCompound;
    private javax.swing.JButton btnUpdateDrug;
    private javax.swing.JButton btnUpdateStudy;
    private javax.swing.JButton btnViewCompoundHis;
    private javax.swing.JButton btnViewDrugHis;
    private javax.swing.JPanel container;
    private javax.swing.JPanel down;
    private javax.swing.JPanel downPanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JSplitPane innerSplitPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbEnterprise;
    private javax.swing.JLabel lbRole;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel pCal;
    private javax.swing.JPanel pChart;
    private javax.swing.JPanel pFunction;
    private javax.swing.JPanel ppFunction;
    private javax.swing.JButton sendMsgBtn;
    private javax.swing.JMenuItem tabAbout2;
    private javax.swing.JMenuItem tabExit;
    private javax.swing.JMenuItem tabHelp;
    private javax.swing.JMenuItem tabHelp1;
    private javax.swing.JMenuItem tabHome;
    private javax.swing.JMenuItem tabHome1;
    private javax.swing.JMenu tabMessage;
    private javax.swing.JMenuItem tabNewCompound;
    private javax.swing.JMenu tabNewDrug;
    private javax.swing.JMenuItem tabNewMsg;
    private javax.swing.JMenu tabNewStudy;
    private javax.swing.JMenu tabNewStudy1;
    private javax.swing.JMenuItem tabShowChannel;
    private javax.swing.JMenuItem tabShowCompoundHis;
    private javax.swing.JMenuItem tabShowDrugHis;
    private javax.swing.JMenuItem tabShowStudyHis;
    private javax.swing.JMenu tabSwitchAccount;
    private javax.swing.JMenuItem tabUpdateCompound;
    private javax.swing.JMenuItem tabUpdateDrug;
    private javax.swing.JPopupMenu.Separator tabUpdateStudy;
    private javax.swing.JPopupMenu.Separator tabUpdateStudy1;
    private javax.swing.JPanel up;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
