/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugEnterprise.ResearcherRole;

import dao.MessageDao;
import dao.UserDao;
import entities.DoctorEnterpriseInfo;
import entities.Message;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ke Wang
 */
public class NewMsgPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;

    /**
     * Creates new form NewMsgPanel
     */
    public NewMsgPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        popupTable();
    }

    private void popupTable() {

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Id");
        dtm.addColumn("Username");
        dtm.addColumn("Enterprise");
        for (DoctorEnterpriseInfo c : new UserDao().joinDoctorUserEnterprise()) {
            dtm.addRow(new Object[]{c, c.getUsername(), c.getEnterprise()});
        }
        tlbDoctor.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tlbDoctor = new javax.swing.JTable();
        sendBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfReceiverID = new javax.swing.JTextField();
        contentTa = new javax.swing.JScrollPane();
        taContent = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(840, 634));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel1.setText("Start New Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 27, -1, -1));

        jLabel11.setText("Please choose a doctor from the table below");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 107, -1, -1));

        tlbDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Name", "Doctor Id", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tlbDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlbDoctorMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tlbDoctor);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 147, 740, 150));

        sendBtn.setText("Send Message");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });
        add(sendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));

        jLabel2.setText("Message Title:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));
        add(tfTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 210, -1));

        jLabel3.setText("Receiver ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));
        add(tfReceiverID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 210, -1));

        taContent.setColumns(20);
        taContent.setRows(5);
        contentTa.setViewportView(taContent);

        add(contentTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 210, 100));

        jLabel8.setText("Content:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        int index = tlbDoctor.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "Please select one receiver");
            return;
        }
        DoctorEnterpriseInfo dei = (DoctorEnterpriseInfo) tlbDoctor.getValueAt(index, 0);
        Message message = new Message(UserDao.getUser().getIdUser(), dei.getId(), taContent.getText(), tfTitle.getText());
        MessageDao dao=new MessageDao();
        dao.save(message);
        JOptionPane.showMessageDialog(null, "congratulations, you have send a message");

        // TODO add your handling code here:
    }//GEN-LAST:event_sendBtnActionPerformed

    private void tlbDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlbDoctorMouseClicked

        int index = tlbDoctor.getSelectedRow();
        DoctorEnterpriseInfo dei = (DoctorEnterpriseInfo) tlbDoctor.getValueAt(index, 0);
        tfReceiverID.setText(dei.getId() + "");

        // TODO add your handling code here:
    }//GEN-LAST:event_tlbDoctorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane contentTa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton sendBtn;
    private javax.swing.JTextArea taContent;
    private javax.swing.JTextField tfReceiverID;
    private javax.swing.JTextField tfTitle;
    private javax.swing.JTable tlbDoctor;
    // End of variables declaration//GEN-END:variables
}
