/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugEnterprise.ResearcherRole;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ke Wang
 */
public class NewStudyPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    
    /**
     * Creates new form DrugPanel
     */
    public NewStudyPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        studyNameTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        studyCatalogCb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        studyPhaseCb = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        drugIdTf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        drugNameTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        titleTf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studyCommentTa = new javax.swing.JTextArea();
        createBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(874, 681));
        setPreferredSize(new java.awt.Dimension(874, 681));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel4.setText("New Study");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 174, 36));

        jLabel6.setText("Study Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));
        add(studyNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 190, -1));

        jLabel1.setText("Study Catalog:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        studyCatalogCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Treatment", "Prevention", "Diagostic", "Screening", "Quality of Life" }));
        add(studyCatalogCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 190, -1));

        jLabel5.setText("Study Phase:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        studyPhaseCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phase 1", "Phase 2", "Phase 3", "Phase 4", "Phase 5" }));
        studyPhaseCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyPhaseCbActionPerformed(evt);
            }
        });
        add(studyPhaseCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 190, -1));

        jLabel14.setText("Drug ID:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));
        add(drugIdTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 200, -1));

        jLabel15.setText("Drug Name:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));
        add(drugNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 200, -1));

        jLabel10.setText("Official Title:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));
        add(titleTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 350, -1));

        jLabel13.setText("Comment:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        studyCommentTa.setColumns(20);
        studyCommentTa.setLineWrap(true);
        studyCommentTa.setRows(5);
        jScrollPane1.setViewportView(studyCommentTa);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 350, 60));

        createBtn.setText("Create Study");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 587, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createBtnActionPerformed

    private void studyPhaseCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyPhaseCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studyPhaseCbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField drugIdTf;
    private javax.swing.JTextField drugNameTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> studyCatalogCb;
    private javax.swing.JTextArea studyCommentTa;
    private javax.swing.JTextField studyNameTf;
    private javax.swing.JComboBox<String> studyPhaseCb;
    private javax.swing.JTextField titleTf;
    // End of variables declaration//GEN-END:variables
}
