/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugEnterprise.ResearcherRole;

import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Ke Wang
 * 
 */
public class ResearcherChannelPanel extends javax.swing.JPanel {
    JPanel container;
    
    /**
     * Creates new form ResearcherChannelPanel
     */
    public ResearcherChannelPanel(JPanel container) {
        initComponents();
        this.container = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        replyBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        msgContentTa1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        msgIdTf1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        msgTitleTf1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        receiverIdTf1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        msgContentTa2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(868, 604));
        setPreferredSize(new java.awt.Dimension(868, 604));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        replyBtn.setText("Reply");
        add(replyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 464, -1, -1));

        msgContentTa1.setColumns(20);
        msgContentTa1.setLineWrap(true);
        msgContentTa1.setRows(5);
        jScrollPane3.setViewportView(msgContentTa1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 378, 400, 80));

        jLabel10.setText("Reply:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 388, -1, -1));

        jPanel1.setMinimumSize(new java.awt.Dimension(810, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message ID", "Message Title", "Receiver ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 766, 150));

        jLabel11.setText("Message ID:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(msgIdTf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, -1));

        jLabel12.setText("Message Title:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        jPanel1.add(msgTitleTf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 210, -1));

        jLabel13.setText("Receiver ID:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        jPanel1.add(receiverIdTf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 210, -1));

        jLabel18.setText("Content:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        msgContentTa2.setColumns(20);
        msgContentTa2.setLineWrap(true);
        msgContentTa2.setRows(5);
        jScrollPane5.setViewportView(msgContentTa2);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 210, 90));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 780, 300));

        jLabel1.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel1.setText("Researcher Message Channel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea msgContentTa1;
    private javax.swing.JTextArea msgContentTa2;
    private javax.swing.JTextField msgIdTf1;
    private javax.swing.JTextField msgTitleTf1;
    private javax.swing.JTextField receiverIdTf1;
    private javax.swing.JButton replyBtn;
    // End of variables declaration//GEN-END:variables
}
