/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugEnterprise.ResearcherRole;

import Business.Study.Study;
import Business.Study.StudyDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ke Wang
 */
public class UpdateStudyPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    StudyDirectory studyDir = new StudyDirectory();
    
    /**
     * Creates new form DrugPanel
     */
    public UpdateStudyPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.studyDir = studyDir;
        populateTable();
    }

    public void populateTable() {
        int rowCount = studyTbl.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) studyTbl.getModel();

        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }

        Study s;
        for (int n = 1; n <= 5; n++) {
            s = studyDir.addStudy();
            switch (n) {
                case 1: {
                    s.setName("Prominent Drug");
                    s.setPhase("1");
                    s.setDrugId("DR76453");
                    s.setDrugName("Atorvastatin");
                    s.setCatalog("Treatment");
                    s.setTitle("Prominent Drug");
                    s.setComment("none");
                    break;
                }
                case 2: {
                    s.setName("Coartem Drug");
                    s.setPhase("1");
                    s.setDrugId("DR0001");
                    s.setDrugName("Coartem");
                    s.setCatalog("Treatment");
                    s.setTitle("Coartem Drug");
                    s.setComment("none");
                    break;
                }
                case 3: {
                    s.setName("Clopidogrel Drug");
                    s.setPhase("1");
                    s.setDrugId("DRG0921");
                    s.setDrugName("Atorvastatin");
                    s.setCatalog("Treatment");
                    s.setTitle("Clopidogrel Drug");
                    s.setComment("none");
                    break;
                }
                case 4: {
                    s.setName("Zolpedim Drug");
                    s.setPhase("1");
                    s.setDrugId("DRG543");
                    s.setDrugName("Zolpedim");
                    s.setCatalog("Treatment");
                    s.setTitle("Zolpedim Drug");
                    s.setComment("none");
                    break;
                }
                case 5: {
                    s.setName("Warfarin Drug");
                    s.setPhase("1");
                    s.setDrugId("DRG5439");
                    s.setDrugName("Warfarin");
                    s.setCatalog("Treatment");
                    s.setTitle("Warfarin Drug");
                    s.setComment("none");
                    break;
                }
                default: {
                    s.setName("Prominent Drug");
                    s.setPhase("1");
                    s.setDrugId("DR76453");
                    s.setDrugName("Atorvastatin");
                    s.setCatalog("Treatment");
                    s.setTitle("Prominent Drug");
                    s.setComment("none");
                    break;
                }
            }
        }

        for (Study study : studyDir.getStudyDir()) {
            Object row[] = new Object[2];
            row[0] = study;
            row[1] = study.getTitle();
            dtm.addRow(row);
        }
    }

    private void displayStudy(Study study) {
        String name = study.getName();
        studyNameTf.setText(name);

        String drugId = study.getDrugId();
        drugIdTf.setText(drugId);

        String drugName = study.getDrugName();
        drugNameTf.setText(drugName);

        String title = study.getTitle();
        titleTf.setText(title);

        String comment = study.getComment();
        studyCommentTa.setText(comment);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        studyTbl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        studyNameTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        studyCatalogCb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        studyPhaseCb = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        drugIdTf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        drugNameTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        titleTf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studyCommentTa = new javax.swing.JTextArea();
        viewBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(876, 731));
        setPreferredSize(new java.awt.Dimension(876, 731));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        studyTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(studyTbl);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 290, 140));
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, -1, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        updateBtn.setText("Update Study");
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 620, -1, -1));

        jLabel15.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel15.setText("Update Study");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, 36));

        jLabel6.setText("Study Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));
        add(studyNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 190, -1));

        jLabel1.setText("Study Catalog:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        studyCatalogCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Treatment", "Prevention", "Diagostic", "Screening", "Quality of Life" }));
        add(studyCatalogCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 190, -1));

        jLabel5.setText("Study Phase:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        studyPhaseCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phase 1", "Phase 2", "Phase 3", "Phase 4", "Phase 5" }));
        studyPhaseCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyPhaseCbActionPerformed(evt);
            }
        });
        add(studyPhaseCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 190, -1));

        jLabel14.setText("Drug ID:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));
        add(drugIdTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 200, -1));

        jLabel17.setText("Drug Name:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));
        add(drugNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 200, -1));

        jLabel10.setText("Official Title:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));
        add(titleTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 200, -1));

        jLabel13.setText("Comment:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        studyCommentTa.setColumns(20);
        studyCommentTa.setLineWrap(true);
        studyCommentTa.setRows(5);
        jScrollPane1.setViewportView(studyCommentTa);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 200, 60));

        viewBtn.setText("View Details");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void studyPhaseCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyPhaseCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studyPhaseCbActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        int row = studyTbl.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Study study = (Study) studyTbl.getValueAt(row, 0);
            displayStudy(study);
        }
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField drugIdTf;
    private javax.swing.JTextField drugNameTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> studyCatalogCb;
    private javax.swing.JTextArea studyCommentTa;
    private javax.swing.JTextField studyNameTf;
    private javax.swing.JComboBox<String> studyPhaseCb;
    private javax.swing.JTable studyTbl;
    private javax.swing.JTextField titleTf;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
