/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugEnterprise.DruggistRole;

import dao.CompoundCatalogDao;
import dao.CompoundDao;
import dao.DrugCatalogDao;
import dao.DrugDao;
import dao.DrugHasCompoundDao;
import entities.Compound;
import entities.CompoundCatalog;
import entities.Drug;
import entities.DrugCatalog;
import entities.DrugHasCompound;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;

/**
 *
 * @author Ke Wang
 *
 */
public class NewDrugPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugPanel
     */
    JPanel container;
    List<DrugHasCompound> listCompound = new ArrayList<DrugHasCompound>();

    public NewDrugPanel(JPanel container) {
        initComponents();
        this.container = container;
        initCompoundCombox();
        initDrugCombox();
        popupTable();
    }

    private void popupTable() {
        tlbCompound.removeAll();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("CompoundId");
        dtm.addColumn("Name");
        dtm.addColumn("Molecular form");
        for (Compound c : new CompoundDao().findAll()) {
            dtm.addRow(new Object[]{c, c.getName(), c.getMolecularFormula()});
        }
        tlbCompound.setModel(dtm);
    }

    private void initDrugCombox() {
        DrugCatalogDao dao = new DrugCatalogDao();

        cbDrugCatalog.removeAllItems();
        for (DrugCatalog d : dao.findAll()) {
            cbDrugCatalog.addItem(d);
        }
    }

    private void initCompoundCombox() {
        CompoundCatalogDao dao = new CompoundCatalogDao();

        drugCatalogCb.removeAllItems();
        for (CompoundCatalog c : dao.findAll()) {
            drugCatalogCb.addItem(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfDrugNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfFormula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbDrugCatalog = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tfUsage = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taIndication = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taManufacture = new javax.swing.JTextArea();
        lb = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taRoute = new javax.swing.JTextArea();
        createBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        drugCatalogCb = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        tlbCompound = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tlbSelectedCompound = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        qsWeight = new javax.swing.JSpinner();
        addBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Drug Number:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        jPanel1.add(tfDrugNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 170, -1));

        jLabel1.setText("Drug Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        jPanel1.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 170, -1));

        jLabel2.setText("Formula:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel1.add(tfFormula, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 170, -1));

        jLabel5.setText("Catalog:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        cbDrugCatalog.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbDrugCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 170, -1));

        jLabel3.setText("Usage:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        jPanel1.add(tfUsage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 170, 80));

        jLabel8.setText("Indication:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        taIndication.setColumns(20);
        taIndication.setLineWrap(true);
        taIndication.setRows(5);
        jScrollPane1.setViewportView(taIndication);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 260, 70));

        jLabel9.setText("Manufacture:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        taManufacture.setColumns(20);
        taManufacture.setLineWrap(true);
        taManufacture.setRows(5);
        jScrollPane2.setViewportView(taManufacture);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 260, 60));

        lb.setText("Route:");
        jPanel1.add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        taRoute.setColumns(20);
        taRoute.setLineWrap(true);
        taRoute.setRows(5);
        jScrollPane3.setViewportView(taRoute);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 260, 60));

        createBtn.setText("Create Drug");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        jLabel11.setText("Find Drug By ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        drugCatalogCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drugCatalogCb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                drugCatalogCbItemStateChanged(evt);
            }
        });
        drugCatalogCb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drugCatalogCbMouseClicked(evt);
            }
        });
        drugCatalogCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugCatalogCbActionPerformed(evt);
            }
        });
        jPanel1.add(drugCatalogCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        tlbCompound.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Formula Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tlbCompound);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 370, 150));

        btnDelete.setText("<<Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        tlbSelectedCompound.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tlbSelectedCompound);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 370, 150));

        jLabel6.setText("Quantity(gram):");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));
        jPanel1.add(qsWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 100, -1));

        addBtn.setText("Add >>");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel10.setText("New Drug");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        add(jPanel1);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        //①new drug get idDrug
        //②insert into DrugHasCompound table
        if ("".equals(tfDrugNumber.getText())) {
            JOptionPane.showMessageDialog(null, "DrugNumber should not be null");
            return;
        }

        String drugNumber = tfDrugNumber.getText();
        //verify
        DrugDao verifyDao = new DrugDao();
        if (1 == verifyDao.findWhetherDrugExist(drugNumber)) {
            JOptionPane.showMessageDialog(null, "drug already exist!");

            return;
        }
        if (0 == listCompound.size()) {
            JOptionPane.showMessageDialog(null, "No compound!");
            return;
        }
        Drug drug = new Drug();
        drug.setDrugNumber(tfDrugNumber.getText());
        drug.setFormula(tfFormula.getText());
        drug.setIndication(taIndication.getText());
        drug.setManufature(taManufacture.getText());
        drug.setRoute(taRoute.getText());
        drug.setName(tfName.getText());
        drug.setUses(tfUsage.getText());
        drug.setIdDrugCatalog(((DrugCatalog) cbDrugCatalog.getSelectedItem()).getIdDrugCatalog());
        try {
            DrugDao dao = new DrugDao();
            dao.save(drug);
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(null, e.getCause().getMessage());

        }

        for (DrugHasCompound dhc : listCompound) {
            dhc.setDrugNumber(tfDrugNumber.getText());
            dhc.setAssignDate(new Date());
            DrugHasCompoundDao dao = new DrugHasCompoundDao();
            dao.save(dhc);
        }

        JOptionPane.showMessageDialog(null, "congratulations, you have created a new compound");

    }//GEN-LAST:event_createBtnActionPerformed

    private void drugCatalogCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugCatalogCbActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_drugCatalogCbActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tlbSelectedCompound.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a Row");
            return;
        }
        DrugHasCompound dhc = (DrugHasCompound) tlbSelectedCompound.getValueAt(selectedRow, 0);
        listCompound.remove(dhc);
        popupSelectCompound();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void popupSelectCompound() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("CompoundId");
//        dtm.addColumn("Name");
        dtm.addColumn("Weight");
        for (DrugHasCompound dhc : listCompound) {
//            dtm.addRow(new Object[]{dhc, dhc.getName(), dhc.getCompoundWeight()});
            dtm.addRow(new Object[]{dhc, dhc.getCompoundWeight()});

        }
        tlbSelectedCompound.setModel(dtm);
    }


    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        int selectedRow = tlbCompound.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a Row");
            return;
        }
        Compound compound = (Compound) tlbCompound.getValueAt(selectedRow, 0);
        int fetchQty = (Integer) qsWeight.getValue();
        if (fetchQty <= 0) {
            JOptionPane.showMessageDialog(null, "Quantity cannot be zero");
            return;
        }
        if (listCompound.size() > 0) {
            for (DrugHasCompound dhc : listCompound) {
                if (dhc.getIdCompound() == compound.getIdCompound()) {
                    JOptionPane.showMessageDialog(null, "Compound has already added");
                    return;
                }
            }
        }

        DrugHasCompound dhc = new DrugHasCompound();
        dhc.setIdCompound(compound.getIdCompound());
        dhc.setCompoundWeight(fetchQty + "");
        //        dhc.setName(compound.getName());
        listCompound.add(dhc);
        popupSelectCompound();
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void drugCatalogCbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drugCatalogCbMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_drugCatalogCbMouseClicked

    private void drugCatalogCbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_drugCatalogCbItemStateChanged

        if (evt.getStateChange() == evt.SELECTED) {

            CompoundCatalog cc = (CompoundCatalog) evt.getItem();
            DefaultTableModel model = (DefaultTableModel) tlbCompound.getModel();
            model.setRowCount(0);
//        DefaultTableModel dtm = new DefaultTableModel();
//        dtm.addColumn("CompoundId");
//        dtm.addColumn("Name");
//        dtm.addColumn("Molecular form");
            for (Compound c : new CompoundDao().findCompoundById(cc.getIdCompoundCatalog() + "")) {
                model.addRow(new Object[]{c, c.getName(), c.getMolecularFormula()});
            }
            tlbCompound.setModel(model);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_drugCatalogCbItemStateChanged

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox cbDrugCatalog;
    private javax.swing.JButton createBtn;
    private javax.swing.JComboBox drugCatalogCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lb;
    private javax.swing.JSpinner qsWeight;
    private javax.swing.JTextArea taIndication;
    private javax.swing.JTextArea taManufacture;
    private javax.swing.JTextArea taRoute;
    private javax.swing.JTextField tfDrugNumber;
    private javax.swing.JTextField tfFormula;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfUsage;
    private javax.swing.JTable tlbCompound;
    private javax.swing.JTable tlbSelectedCompound;
    // End of variables declaration//GEN-END:variables
}
