package entities;
// Generated Dec 2, 2016 12:00:50 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Compound generated by hbm2java
 */
@Entity
@Table(name="Compound"
    ,catalog="MedicalEcoSystem"
)
public class Compound  implements java.io.Serializable {


     private Integer idCompound;
     private String name;
     private String description;
     private String molecularFormula;
     private String MolecularWeight;

     private String molecularStructure;
//     private Integer idDrug;
     private int idCompoundCatalog;

    public Compound() {
    }

	
    public Compound(int idCompoundCatalog) {
        this.idCompoundCatalog = idCompoundCatalog;
    }
    public Compound(String name, String description, String molecularFormula, String molecularStructure, Integer idDrug, int idCompoundCatalog) {
       this.name = name;
       this.description = description;
       this.molecularFormula = molecularFormula;
       this.molecularStructure = molecularStructure;
//       this.idDrug = idDrug;
       this.idCompoundCatalog = idCompoundCatalog;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCompound", unique=true, nullable=false)
    public Integer getIdCompound() {
        return this.idCompound;
    }
    
    public void setIdCompound(Integer idCompound) {
        this.idCompound = idCompound;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="molecularFormula", length=45)
    public String getMolecularFormula() {
        return this.molecularFormula;
    }
    
    public void setMolecularFormula(String molecularFormula) {
        this.molecularFormula = molecularFormula;
    }
    
    @Column(name="MolecularWeight", length=45)
    public String getMolecularWeight() {
        return MolecularWeight;
    }

    public void setMolecularWeight(String MolecularWeight) {
        this.MolecularWeight = MolecularWeight;
    }
     

    
    @Column(name="molecularStructure", length=45)
    public String getMolecularStructure() {
        return this.molecularStructure;
    }
    
    public void setMolecularStructure(String molecularStructure) {
        this.molecularStructure = molecularStructure;
    }

    
//    @Column(name="idDrug")
//    public Integer getIdDrug() {
//        return this.idDrug;
//    }
//    
//    public void setIdDrug(Integer idDrug) {
//        this.idDrug = idDrug;
//    }

    
    @Column(name="idCompoundCatalog", nullable=false)
    public int getIdCompoundCatalog() {
        return this.idCompoundCatalog;
    }
    
    public void setIdCompoundCatalog(int idCompoundCatalog) {
        this.idCompoundCatalog = idCompoundCatalog;
    }

    @Override
    public String toString() {
        return idCompound+""; //To change body of generated methods, choose Tools | Templates.
    }




}


