package entities;
// Generated Dec 2, 2016 12:00:50 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CompoundCatalog generated by hbm2java
 */
@Entity
@Table(name="CompoundCatalog"
    ,catalog="MedicalEcoSystem"
)
public class CompoundCatalog  implements java.io.Serializable {


     private Integer idCompoundCatalog;
     private String name;

    public CompoundCatalog() {
    }

    public CompoundCatalog(String name) {
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCompoundCatalog", unique=true, nullable=false)
    public Integer getIdCompoundCatalog() {
        return this.idCompoundCatalog;
    }
    
    public void setIdCompoundCatalog(Integer idCompoundCatalog) {
        this.idCompoundCatalog = idCompoundCatalog;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return name; //To change body of generated methods, choose Tools | Templates.
    }



    
}


