package entities;
// Generated Dec 2, 2016 12:00:50 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="Country"
    ,catalog="MedicalEcoSystem"
    , uniqueConstraints = @UniqueConstraint(columnNames="country") 
)
public class Country  implements java.io.Serializable {


     private Integer idCountry;
     private String country;

    public Country() {
    }

    public Country(String country) {
       this.country = country;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCountry", unique=true, nullable=false)
    public Integer getIdCountry() {
        return this.idCountry;
    }
    
    public void setIdCountry(Integer idCountry) {
        this.idCountry = idCountry;
    }

    
    @Column(name="country", unique=true, length=45)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


