package entities;
// Generated Dec 2, 2016 12:00:50 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name="Doctor"
    ,catalog="MedicalEcoSystem"
)
public class Doctor  implements java.io.Serializable {


     private int idUser;
     private int idSpeciality;

    public Doctor() {
    }

    public Doctor(int idUser, int idSpeciality) {
       this.idUser = idUser;
       this.idSpeciality = idSpeciality;
    }
   
     @Id 

    
    @Column(name="idUser", unique=true, nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="idSpeciality", nullable=false)
    public int getIdSpeciality() {
        return this.idSpeciality;
    }
    
    public void setIdSpeciality(int idSpeciality) {
        this.idSpeciality = idSpeciality;
    }




}


