package entities;
// Generated Dec 3, 2016 8:52:03 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DrugHasCompound generated by hbm2java
 */
@Entity
@Table(name = "Drug_has_Compound", catalog = "MedicalEcoSystem", uniqueConstraints = @UniqueConstraint(columnNames = {"drugNumber", "idCompound", "compoundWeight"})
)
public class DrugHasCompound implements java.io.Serializable {

    private Integer id;
//    private int idDrug;
    private int idCompound;
    private String compoundWeight;
    private String drugNumber;
    private Date assignDate;

//    private String name;
//
//    public String getName() {
//        return name;
//    }
//
//    public void setName(String name) {
//        this.name = name;
//    }
    @Column(name = "drugNumber", length = 45)
    public String getDrugNumber() {
        return drugNumber;
    }

    public void setDrugNumber(String drugNumber) {
        this.drugNumber = drugNumber;
    }

    public DrugHasCompound() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

//    @Column(name = "idDrug", nullable = false)
//    public int getIdDrug() {
//        return this.idDrug;
//    }
//
//    public void setIdDrug(int idDrug) {
//        this.idDrug = idDrug;
//    }
    @Temporal(TemporalType.DATE)
    @Column(name = "assignDate", length = 10)
    public Date getAssignDate() {
        return assignDate;
    }

    public void setAssignDate(Date assignDate) {
        this.assignDate = assignDate;
    }
    
    


    @Column(name = "idCompound", nullable = false)
    public int getIdCompound() {
        return this.idCompound;
    }

    public void setIdCompound(int idCompound) {
        this.idCompound = idCompound;
    }

    @Column(name = "compoundWeight", length = 45)
    public String getCompoundWeight() {
        return this.compoundWeight;
    }

    public void setCompoundWeight(String compoundWeight) {
        this.compoundWeight = compoundWeight;
    }

    @Override
    public String toString() {
        return idCompound + ""; //To change body of generated methods, choose Tools | Templates.
    }

}
