package entities;
// Generated Dec 2, 2016 12:00:50 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Druggist generated by hbm2java
 */
@Entity
@Table(name="Druggist"
    ,catalog="MedicalEcoSystem"
)
public class Druggist  implements java.io.Serializable {


     private int idUser;

    public Druggist() {
    }

    public Druggist(int idUser) {
       this.idUser = idUser;
    }
   
     @Id 

    
    @Column(name="idUser", unique=true, nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }




}


