package entities;
// Generated Dec 2, 2016 12:00:50 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnterpriseId generated by hbm2java
 */
@Embeddable
public class EnterpriseId  implements java.io.Serializable {


     private int idEnterprise;
     private int idCity;

    public EnterpriseId() {
    }

    public EnterpriseId(int idEnterprise, int idCity) {
       this.idEnterprise = idEnterprise;
       this.idCity = idCity;
    }
   


    @Column(name="idEnterprise", nullable=false)
    public int getIdEnterprise() {
        return this.idEnterprise;
    }
    
    public void setIdEnterprise(int idEnterprise) {
        this.idEnterprise = idEnterprise;
    }


    @Column(name="idCity", nullable=false)
    public int getIdCity() {
        return this.idCity;
    }
    
    public void setIdCity(int idCity) {
        this.idCity = idCity;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EnterpriseId) ) return false;
		 EnterpriseId castOther = ( EnterpriseId ) other; 
         
		 return (this.getIdEnterprise()==castOther.getIdEnterprise())
 && (this.getIdCity()==castOther.getIdCity());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEnterprise();
         result = 37 * result + this.getIdCity();
         return result;
   }   


}


