package entities;
// Generated Dec 11, 2016 3:45:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Enterprise generated by hbm2java
 */
@Entity
@Table(name="Enterprise"
    ,catalog="MedicalEcoSystem"
)
public class Enterprise  implements java.io.Serializable {


     private Integer idEnterprise;
     private City city;
     private String name;
     private String type;

    public Enterprise() {
    }

	
    public Enterprise(City city, String name, String type) {
        this.city = city;
        this.name = name;
        this.type = type;
    }
 
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEnterprise", unique=true, nullable=false)
    public Integer getIdEnterprise() {
        return this.idEnterprise;
    }
    
    public void setIdEnterprise(Integer idEnterprise) {
        this.idEnterprise = idEnterprise;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCity", nullable=false)
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="type", nullable=false, length=18)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return name; //To change body of generated methods, choose Tools | Templates.
    }






}


