package entities;
// Generated Dec 2, 2016 12:00:50 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "Message", catalog = "MedicalEcoSystem"
)
public class Message implements java.io.Serializable {

    private Integer idMessage;
    private Integer sender;
    private Integer receiver;
    private String content;
    private String title;

    public Message() {
    }

    public Message(Integer sender, Integer receiver, String content, String title) {
        this.sender = sender;
        this.receiver = receiver;
        this.content = content;
        this.title = title;
    }

    @Column(name = "title", length = 45)

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idMessage", unique = true, nullable = false)
    public Integer getIdMessage() {
        return idMessage;
    }

    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }

    @Column(name = "sender")

    public Integer getSender() {
        return sender;
    }

    public void setSender(Integer sender) {
        this.sender = sender;
    }

    @Column(name = "receiver")

    public Integer getReceiver() {
        return receiver;
    }

    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    @Column(name = "content", length = 100)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        return idMessage+"" ;//To change body of generated methods, choose Tools | Templates.
    }
    

}
