package entities;
// Generated Dec 2, 2016 12:00:50 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="Role"
    ,catalog="MedicalEcoSystem"
    , uniqueConstraints = {@UniqueConstraint(columnNames="name"), @UniqueConstraint(columnNames="Rolecol")} 
)
public class Role  implements java.io.Serializable {


     private Integer idRole;
     private String name;
     private String rolecol;

    public Role() {
    }

	
    public Role(String name) {
        this.name = name;
    }
    public Role(String name, String rolecol) {
       this.name = name;
       this.rolecol = rolecol;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idRole", unique=true, nullable=false)
    public Integer getIdRole() {
        return this.idRole;
    }
    
    public void setIdRole(Integer idRole) {
        this.idRole = idRole;
    }

    
    @Column(name="name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Rolecol", unique=true, length=45)
    public String getRolecol() {
        return this.rolecol;
    }
    
    public void setRolecol(String rolecol) {
        this.rolecol = rolecol;
    }




}


