package entities;
// Generated Dec 2, 2016 12:00:50 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudyType generated by hbm2java
 */
@Entity
@Table(name="StudyType"
    ,catalog="MedicalEcoSystem"
)
public class StudyType  implements java.io.Serializable {


     private int idStudyType;
     private String name;

    public StudyType() {
    }

	
    public StudyType(int idStudyType) {
        this.idStudyType = idStudyType;
    }
    public StudyType(int idStudyType, String name) {
       this.idStudyType = idStudyType;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="idStudyType", unique=true, nullable=false)
    public int getIdStudyType() {
        return this.idStudyType;
    }
    
    public void setIdStudyType(int idStudyType) {
        this.idStudyType = idStudyType;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


