/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import UserInterface.DrugEnterprise.DrugEnterprise;
import UserInterface.HospitalEnterprise.HospitalJFrame;
import dao.CityDao;
import dao.EnterpriseDao;
import dao.UserDao;
import entities.City;
import entities.Enterprise;
import entities.User;
import java.awt.Component;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jdatepicker.DatePanel;
import org.jdatepicker.JDatePanel;

/**
 *
 * @author GladysWang
 */
public class SystemAdminJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DrugEnterprise
     */
    JPanel userProcessContainer;

    public SystemAdminJFrame() {

        setExtendedState(JFrame.MAXIMIZED_BOTH);

        initComponents();
//        initCalender();
        popupTable();
        initUserInfo();

    }
 public void initUserInfo() {
        User user = UserDao.getUser();
        lbEnterprise.setText(new UserDao().getEnterpriseNameById(user.getIdEnterprise() + ""));
        lbRole.setText(user.getRole());
        lbUser.setText(user.getUsername());
    }

    private void popupTable() {

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Network");

        for (City c : new CityDao().findAll()) {
            dtm.addRow(new Object[]{c});
        }
        tlbCity.setModel(dtm);
    }

    public void initCalender() {
        DatePanel panel = new JDatePanel();
        panel.setShowYearButtons(true);
        pCal.add((Component) panel);

        panel.setShowYearButtons(false);
        pCal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jSplitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        innerSplitPane = new javax.swing.JSplitPane();
        upperPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbRole = new javax.swing.JLabel();
        lbEnterprise = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        downPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        down = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAddNetwork1 = new javax.swing.JButton();
        pCal = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        ppFunction = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbEnterprise = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tlbCity = new javax.swing.JTable();
        compoundTbl = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        tfNetwork = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAddNetwork = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfEnterprise = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        existedPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tlbUser = new javax.swing.JTable();
        btnAddNetwork2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        tabSwitchAccount = new javax.swing.JMenu();
        tabHome = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        tabHome1 = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        tabExit = new javax.swing.JMenuItem();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 650));

        jSplitPane.setDividerLocation(250);
        jSplitPane.setDividerSize(5);
        jSplitPane.setPreferredSize(new java.awt.Dimension(1000, 650));

        leftPanel.setPreferredSize(new java.awt.Dimension(300, 650));
        leftPanel.setLayout(new java.awt.BorderLayout());

        innerSplitPane.setDividerLocation(180);
        innerSplitPane.setDividerSize(0);
        innerSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        innerSplitPane.setMinimumSize(new java.awt.Dimension(200, 650));
        innerSplitPane.setPreferredSize(new java.awt.Dimension(250, 336));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Welcome!");

        lbRole.setText("Gruggist");

        lbEnterprise.setText("Research Instute:");

        lbUser.setText("Gladys");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/0.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbRole)
                        .addGap(37, 37, 37)
                        .addComponent(lbUser))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbEnterprise))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel12))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRole)
                    .addComponent(lbUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEnterprise)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        innerSplitPane.setTopComponent(upperPanel);

        downPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        downPanel.setLayout(new java.awt.CardLayout());

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(200, 400));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(250, 300));

        btnAddNetwork1.setText("Add User");
        btnAddNetwork1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNetwork1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnAddNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnAddNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        down.add(jPanel1);

        jSplitPane1.setRightComponent(down);

        pCal.setBackground(new java.awt.Color(204, 204, 204));
        pCal.setForeground(new java.awt.Color(204, 204, 204));
        pCal.setAlignmentX(0.0F);
        pCal.setAlignmentY(0.0F);
        pCal.setMinimumSize(new java.awt.Dimension(230, 234));
        pCal.setPreferredSize(new java.awt.Dimension(240, 220));
        pCal.setLayout(new java.awt.CardLayout());
        jSplitPane1.setLeftComponent(pCal);

        downPanel.add(jSplitPane1, "card2");

        innerSplitPane.setRightComponent(downPanel);

        leftPanel.add(innerSplitPane, java.awt.BorderLayout.CENTER);

        jSplitPane.setLeftComponent(leftPanel);

        container.setLayout(new java.awt.CardLayout());

        ppFunction.setPreferredSize(new java.awt.Dimension(252, 180));

        tlbEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tlbEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlbEnterpriseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tlbEnterprise);

        tlbCity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tlbCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlbCityMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tlbCity);

        compoundTbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        compoundTbl.setMaximumSize(new java.awt.Dimension(500, 800));

        jPanel6.setMaximumSize(new java.awt.Dimension(302, 422));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setText("Network:");

        jButton1.setText("Update Network");

        btnAddNetwork.setText("Add Network");
        btnAddNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNetworkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(btnAddNetwork)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel3.setText("Enterprise:");

        jButton3.setText("Add Enterprise");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Update Enterprise");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 220, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        compoundTbl.addTab("update", jPanel6);

        existedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tlbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tlbUser);

        existedPanel.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 310, 510));

        btnAddNetwork2.setText("Add User");
        btnAddNetwork2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNetwork2ActionPerformed(evt);
            }
        });
        existedPanel.add(btnAddNetwork2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 120, 40));

        compoundTbl.addTab("user info", existedPanel);

        javax.swing.GroupLayout ppFunctionLayout = new javax.swing.GroupLayout(ppFunction);
        ppFunction.setLayout(ppFunctionLayout);
        ppFunctionLayout.setHorizontalGroup(
            ppFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFunctionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compoundTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ppFunctionLayout.setVerticalGroup(
            ppFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppFunctionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ppFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compoundTbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ppFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        container.add(ppFunction, "card2");

        jSplitPane.setRightComponent(container);

        getContentPane().add(jSplitPane, java.awt.BorderLayout.CENTER);

        tabSwitchAccount.setText("EcoSystem");

        tabHome.setText("Hospital");
        tabHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabHomeActionPerformed(evt);
            }
        });
        tabSwitchAccount.add(tabHome);
        tabSwitchAccount.add(jSeparator19);

        tabHome1.setText("Drug Enterprise");
        tabHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabHome1ActionPerformed(evt);
            }
        });
        tabSwitchAccount.add(tabHome1);
        tabSwitchAccount.add(jSeparator20);

        tabExit.setText("Exit");
        tabExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabExitActionPerformed(evt);
            }
        });
        tabSwitchAccount.add(tabExit);

        jMenuBar1.add(tabSwitchAccount);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabExitActionPerformed

    private void tabHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabHomeActionPerformed

        try {
            new HospitalJFrame().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(HospitalJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(HospitalJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        System.gc();

        // TODO add your handling code here:
    }//GEN-LAST:event_tabHomeActionPerformed

    private void btnAddNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNetworkActionPerformed

        new AddNetworkDialog(this).setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddNetworkActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        new AddEnterpriseDialog(this).setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tlbCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlbCityMouseClicked

        int index = tlbCity.getSelectedRow();
        City city = (City) tlbCity.getValueAt(index, 0);

        EnterpriseDao dao = new EnterpriseDao();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Name");
        dtm.addColumn("Type");

        for (Enterprise enterprise : dao.searchEnterpriseByIdCity(city.getId() + "")) {
            dtm.addRow(new Object[]{enterprise, enterprise.getType()});
        }
        tlbEnterprise.setModel(dtm);
        tfNetwork.setText(city.getCity());
        // TODO add your handling code here:
    }//GEN-LAST:event_tlbCityMouseClicked

    private void tlbEnterpriseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlbEnterpriseMouseClicked

        int index = tlbEnterprise.getSelectedRow();
        Enterprise enterprise = (Enterprise) tlbEnterprise.getValueAt(index, 0);
        tfEnterprise.setText(enterprise.getName());

        UserDao dao = new UserDao();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Username");
        dtm.addColumn("Role");
        List<User> list = dao.searchUserByIdEnterprise(enterprise.getIdEnterprise() + "");
        if (list.size()>0) {
            for (User user : list) {
                dtm.addRow(new Object[]{user, user.getRole()});

            }
            tlbUser.setModel(dtm);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tlbEnterpriseMouseClicked

    private void btnAddNetwork1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNetwork1ActionPerformed
        new NewJDialog(this).setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddNetwork1ActionPerformed

    private void btnAddNetwork2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNetwork2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddNetwork2ActionPerformed

    private void tabHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabHome1ActionPerformed

        new DrugEnterprise().setVisible(true);

        dispose();
        System.gc();

        // TODO add your handling code here:
    }//GEN-LAST:event_tabHome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemAdminJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNetwork;
    private javax.swing.JButton btnAddNetwork1;
    private javax.swing.JButton btnAddNetwork2;
    private javax.swing.JTabbedPane compoundTbl;
    private javax.swing.JPanel container;
    private javax.swing.JPanel down;
    private javax.swing.JPanel downPanel;
    private javax.swing.JPanel existedPanel;
    private javax.swing.JSplitPane innerSplitPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbEnterprise;
    private javax.swing.JLabel lbRole;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel pCal;
    private javax.swing.JPanel ppFunction;
    private javax.swing.JMenuItem tabExit;
    private javax.swing.JMenuItem tabHome;
    private javax.swing.JMenuItem tabHome1;
    private javax.swing.JMenu tabSwitchAccount;
    private javax.swing.JTextField tfEnterprise;
    private javax.swing.JTextField tfNetwork;
    private javax.swing.JTable tlbCity;
    private javax.swing.JTable tlbEnterprise;
    private javax.swing.JTable tlbUser;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
