/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalEnterprise.DoctorRole;

import dao.DrugCatalogDao;
import dao.JoinSeletedCompoundDao;
import entities.Drug;
import entities.JoinSelectedCompound;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ke Wang
 */
public class DoctorChannel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    
    /**
     * Creates new form ChanelForDrug
     */
    public DoctorChannel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        msgIdTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        msgTitleTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        receiverIdTf = new javax.swing.JTextField();
        studyIdTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        studyNameTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        studyPhaseTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sendDateCb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        contentTa = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        newMsgBtn = new javax.swing.JButton();
        replyBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(907, 605));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Doctor Channel");

        msgTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message ID", "Message Title", "Receiver ID", "Status", "Study Name", "Send Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        msgTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msgTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(msgTbl);

        jLabel1.setText("Message ID:");

        jLabel2.setText("Message Title:");

        jLabel3.setText("Receiver ID:");

        jLabel5.setText("Study ID:");

        jLabel6.setText("Study Name:");

        jLabel7.setText("Study Phase:");

        jLabel9.setText("Send Date:");

        sendDateCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Content:");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        contentTa.setViewportView(jTextArea1);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        newMsgBtn.setText("Write New Message");
        newMsgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMsgBtnActionPerformed(evt);
            }
        });

        replyBtn.setText("Reply");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(718, 718, 718)
                        .addComponent(replyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(msgIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel5)
                        .addGap(43, 43, 43)
                        .addComponent(studyIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(msgTitleTf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel6)
                        .addGap(21, 21, 21)
                        .addComponent(studyNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(receiverIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel7)
                        .addGap(21, 21, 21)
                        .addComponent(studyPhaseTf, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel9)
                        .addGap(43, 43, 43)
                        .addComponent(sendDateCb, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel8)
                        .addGap(46, 46, 46)
                        .addComponent(contentTa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(backBtn)
                        .addGap(472, 472, 472)
                        .addComponent(newMsgBtn)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(replyBtn)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(msgIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(studyIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(msgTitleTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(studyNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(receiverIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(studyPhaseTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9))
                    .addComponent(sendDateCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(contentTa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addComponent(newMsgBtn))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void newMsgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMsgBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newMsgBtnActionPerformed

    private void msgTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msgTblMouseClicked
        // TODO add your handling code here:
        int index = msgTbl.getSelectedRow();
        Drug c = (Drug) msgTbl.getValueAt(index, 0);
        //do this like click the view button in previous labs
        
        
//        tfName.setText(c.getName());
//        tfDrugNumber.setText(c.getDrugNumber());
//        tfFormula.setText(c.getFormula());
//        taRoute.setText(c.getRoute());
//        tfUsage.setText(c.getUses());
//        taManu.setText(c.getManufature());
//        taIndication.setText(c.getIndication());
//        DrugCatalogDao dao = new DrugCatalogDao();
//        cbCatalog.getModel().setSelectedItem(dao.find(c.getIdDrugCatalog()));
//        //show compound detail through drug number
//        JoinSeletedCompoundDao jsccd = new JoinSeletedCompoundDao();
////        dscDao.findCompoundByDrugNumber(c.getDrugNumber());
//        DefaultTableModel dtm = new DefaultTableModel();
//        dtm.addColumn("Id");
//        dtm.addColumn("Name");
//        dtm.addColumn("Formula");
//        dtm.addColumn("Weight");
//        dtm.addColumn("AssignDate");
//
//        for (JoinSelectedCompound jsc : jsccd.findCompoundByDrugNumber(c.getDrugNumber())) {
//            dtm.addRow(new Object[]{jsc, jsc.getName(), jsc.getFormula(), jsc.getWeight(), jsc.getAssignDate()});
//        }
//        tlbCompound.setModel(dtm);
    }//GEN-LAST:event_msgTblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane contentTa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField msgIdTf;
    private javax.swing.JTable msgTbl;
    private javax.swing.JTextField msgTitleTf;
    private javax.swing.JButton newMsgBtn;
    private javax.swing.JTextField receiverIdTf;
    private javax.swing.JButton replyBtn;
    private javax.swing.JComboBox<String> sendDateCb;
    private javax.swing.JTextField studyIdTf;
    private javax.swing.JTextField studyNameTf;
    private javax.swing.JTextField studyPhaseTf;
    // End of variables declaration//GEN-END:variables
}
